version: '3.8'
services:
    keycloak:
        image: keycloak/keycloak:23.0
        command: start-dev --import-realm
        networks:
            - front-tier
            - back-tier
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KEYCLOAK_IMPORT=/realm_import_config
        volumes:
            - ./keycloak:/opt/keycloak/data/import
    web-app:
        build: web-app
        networks:
            - front-tier
    api-gateway:
        build: api-gateway
        networks:
            - front-tier
            - back-tier
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        networks:
            - front-tier
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
    front-tier: {}
    back-tier: {}
